server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: risk-assessment
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://${risk.mysql.ip}:${risk.mysql.port}/${risk.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: ${risk.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${risk.mysql.username}
  redis:
    port: ${risk.redis.port}
    password: ${risk.redis.password}
    host: ${risk.redis.host}
    database: 2
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
logging:
  level:
    org.springframework.web: INFO
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  jackson:
    serialization:
      write-dates-as-timestamps: true