risk:
  mysql:
    ip: 43.139.167.19
    username: root
    password: yushang001
    port: 3307
    db: risk_assessment
  redis:
    host: 43.139.167.19
    port: 6379
    password: yushang001
yushang:
  jwt:
    secret: 12srtgdf213