risk:
  mysql:
    ip: 127.0.0.1
    username: root
    password: yushang001
    port: 3307
    db: risk_assessment
  redis:
    host: 127.0.0.1
    port: 6379
    password: yushang001
yushang:
  jwt:
    secret: 12srtgdf213
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: yushang001