---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zlp.
--- DateTime: 2024/1/12 14:18
---
local k1 = KEYS[1]
local k2 = KEYS[2]

-- 从k1中获取值v1
local v1 = redis.call("GET", k1)
if v1 == "0" then
    return
end
if v1 then
    -- 将v1放入k2的ZSET中，分数为当前时间戳（毫秒）
    redis.call("ZADD", k2, redis.call("TIME")[1] * 1000 + redis.call("TIME")[2] / 1000, v1)

    -- 清空k1的值
    redis.call("SET", k1, "0")
end
